name: jellyfin_dart
version: 1.0.0
description: Jellyfin API client for Dart
homepage: homepage


environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  dio: '^5.7.0'
  equatable: '^2.0.7'
  copy_with_extension: '^7.1.0'
  json_annotation: '^4.9.0'

dev_dependencies:
  build_runner: any
  copy_with_extension_gen: ^7.1.0
  json_serializable: '^6.9.3'
  test: '^1.16.0'
